version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      docusaurus:
        patterns:
          - '*docusaurus*'
      linters:
        patterns:
          - '*lint*'
          - 'globals'
          - 'husky'
          - 'prettier'
    ignore:
      # Pin key docusaurus dependencies to major versions
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: '@mdx-js/react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'prism-react-renderer'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
